d2g_llm_filling_llm:v1:
  config:
    name: o3-mini
    temperature: 1
  model_type: llm
d2g_llm_grouping_llm:v1:
  config:
    name: gpt-4o-latest
    temperature: 0
  model_type: llm
d2g_llm_sim_model:v1:
  config:
    model_kwargs:
      device: cpu
    model_name: cointegrated/LaBSE-en-ru
  model_type: emb
my_model:
  config:
    name: gpt-3.5-turbo
  model_type: llm
