my_filling_model:
  config:
    model_name: gpt-3.5-turbo
  model_type: ChatOpenAI
three_stages_llm_formatting_llm:v1:
  config:
    model_name: gpt-4o-mini
    temperature: 0
  model_type: ChatOpenAI
three_stages_llm_grouping_llm:v1:
  config:
    model_name: chatgpt-4o-latest
    temperature: 0
  model_type: ChatOpenAI
three_stages_llm_sim_model:v1:
  config:
    model_kwargs:
      device: cpu
    model_name: BAAI/bge-m3
  model_type: HuggingFaceEmbeddings
