services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env

    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PROMPT_CACHE_PASSWORD=${PROMPT_CACHE_PASSWORD}

    networks:
      - postgres-network
    command: ["postgres", "-c", "app.prompt_cache_password=${PROMPT_CACHE_PASSWORD}"]

volumes:
  pgdata:


networks:
  postgres-network:
    driver: bridge
