CREATE TABLE prompt_cache (
    id INTEGER PRIMARY KEY,
    prompt TEXT NOT NULL,
    response TEXT NOT NULL,
    llm TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER :'PROMPT_CACHE_USER' WITH PASSWORD :'PROMPT_CACHE_PASSWORD';

GRANT CONNECT ON DATABASE postgres TO :'PROMPT_CACHE_USER';
GRANT USAGE ON SCHEMA public TO :'PROMPT_CACHE_USER';
GRANT SELECT, INSERT ON prompt_cache TO :'PROMPT_CACHE_USER';