name: build_and_publish_docs

on:
  push:
    branches:
    - dev
    - master
    - test/**
  pull_request:
    branches:
    - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/master' }}

jobs:
  publish:
    name: build and publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python '3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.6'

      - name: setup poetry and install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m poetry install --with docs --all-extras --no-ansi --no-interaction
          # Explicitly install theme and its dependencies
          python -m poetry run pip install pydata-sphinx-theme sphinx-copybutton

      - name: build documentation
        run: |
          # Force clean build
          rm -rf docs/build/
          python -m poetry run sphinx-build -b html -a -E docs/source/ docs/build/

      - name: check build contents
        run: |
          echo "Checking build directory contents:"
          ls -la docs/build/
          echo "Checking for CSS files:"
          find docs/build/ -name "*.css"

      - name: save branch name without slashes
        if: ${{ github.ref != 'refs/heads/master' }}
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          BRANCH_NAME=${{ env.BRANCH_NAME }}
          BRANCH_NAME=${BRANCH_NAME////_}
          echo BRANCH_NAME=${BRANCH_NAME} >> $GITHUB_ENV

      - name: save artifact
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('github-pages-for-branch-{0}', env.BRANCH_NAME) }}
          path: docs/build/
          retention-days: 3

      - name: deploy website for master
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: docs/build/
          target-folder: master # Deploy to root for master branch
          single-commit: false
          clean: True

      - name: deploy website for dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: docs/build/
          target-folder: dev # Deploy to /dev subdirectory
          single-commit: false # Keep history for dev branch
          clean: True

      - name: print link to the documentation
        run: |
          echo "https://deeppavlov.github.io/dialogue2graph/${{ github.head_ref || github.ref_name }}"
