name: coverage

on:
  push:
    branches: '**'
  pull_request:
    branches:
    - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/master' }}

jobs:
  test_cov_ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python '3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: setup poetry and install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m poetry install --with tests --no-ansi --no-interaction

      - name: run check_dg_metrics
        run: |
          python -m poetry run poe coverage || exit 1
