name: test_release

on:
  push:
    branches: '**'
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main' }}

jobs:
  test_ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python '3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: setup poetry and install dependencies
        run: |
          pipx install poetry==1.8.4
      
      - name: build release
        run: |
          poetry build
    
      - name: install release
        run: |
          python -m venv test_env && source test_env/bin/activate
          pip install ./dist/your_package_name-*.whl

      - name: Test installed package
        run: |
          python -m venv test_env
          source test_env/bin/activate
          pip install ./dist/*.whl
          pip install pytest  # If pytest isn't in your package deps
          pytest