name: test_release

on:
  push:
    branches: '**'
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main' }}

jobs:
  test_full:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [macOS-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup poetry and install dependencies
        run: |
          pipx install poetry==1.8.4
      
      - name: build release
        run: |
          poetry build
    
      - name: install release
        run: |
          python -m venv test_env && source test_env/bin/activate
          pip install ./dist/dialogue2graph-*.whl

      - name: Test installed package
        shell: bash
        run: |
          python -m venv test_env
          source test_env/bin/activate
          pip install ./dist/*.whl
          pip install pytest  # If pytest isn't in your package deps
          pytest